-- kb_articles.category was still the original fixed ticket_category enum,
-- while tickets.category has long since moved to free text (issue_categories).
-- Widen it so KB articles can use the same Odoo & Textile category slugs as
-- tickets, otherwise every Odoo article would be forced into one bucket.
ALTER TABLE public.kb_articles ALTER COLUMN category DROP DEFAULT;
ALTER TABLE public.kb_articles ALTER COLUMN category TYPE text USING category::text;
ALTER TABLE public.kb_articles ALTER COLUMN category SET DEFAULT 'other';

-- 20 real self-help articles, one per Odoo & Textile category, covering the
-- issues that come up running Odoo in a textile manufacturing operation.
INSERT INTO public.kb_articles (slug, title, category, content) VALUES
('odoo-wrong-company-data', 'Odoo shows the wrong company or department data', 'odoo-functional-support',
'1. Check the company switcher in the top right corner of Odoo and confirm the correct company or branch is selected.\n2. Go to your user profile (top right avatar) and check Preferences to confirm the correct default company is set.\n3. If you were recently moved between departments, ask MIS to update your allowed companies under Settings > Users.\n4. Log out completely, clear the browser cache for the Odoo tab, and log back in.\n5. If the wrong data still appears after switching, note the exact screen and record number and open a ticket.'),

('odoo-custom-request-process', 'How to request a new custom field, screen, or module in Odoo', 'odoo-custom-development',
'Before opening a ticket for a custom development request, prepare the following so the MIS development team can scope it correctly:\n1. Which Odoo module and screen the change belongs to (example: Manufacturing > Work Orders).\n2. The exact business reason the change is needed and who will use it.\n3. What data or field is missing today, and what value or format it should have.\n4. Any similar screen or report already in Odoo that can be used as a reference.\n5. Whether this is needed for one department or company wide.\nSubmit a ticket under category Odoo Custom Development with these details attached. Small changes are usually reviewed within 2-3 business days; larger module changes go through a scoping call first.'),

('odoo-error-traceback', 'Odoo shows a red error banner or technical error when saving', 'odoo-bug-fix',
'1. Do not click away from the screen immediately. Take a screenshot of the full error message, including the technical details if a Show Details or Traceback link appears.\n2. Note the exact record you were editing (order number, invoice number, or record ID shown in the browser URL).\n3. Note the exact steps you took right before the error appeared.\n4. Refresh the page once and try the same action again to confirm it is not a one-time glitch.\n5. If it repeats, open a ticket under Odoo Bug Fix with the screenshot, record number, and steps. Do not keep retrying the same save many times, as it can create duplicate records.'),

('odoo-report-wrong-totals', 'Odoo PDF or Excel report is missing data or shows wrong totals', 'odoo-report-development',
'1. Confirm the date range and filters used when generating the report match what you expect.\n2. Check whether the missing records are still in Draft status. Most financial and production reports only include Posted or Confirmed records.\n3. Re-generate the report after refreshing the page, in case it was cached from an earlier run.\n4. Compare against the underlying list view (for example Accounting > Invoices) filtered the same way, to confirm whether the data itself is missing or only the report layout is wrong.\n5. If the report layout itself needs a new column, subtotal, or grouping, open a ticket under Odoo Report Development with a description or sketch of the expected layout.'),

('odoo-approval-stuck', 'A purchase or sales order is stuck waiting for approval', 'odoo-workflow-approval',
'1. Open the order and check the top status bar for who the current approver is.\n2. Confirm the approver is not on leave. If they are, ask their manager or MIS to reassign the approval.\n3. Check that the order amount does not exceed a limit that requires a higher-level approver; large orders may need a second approval step.\n4. If the approve button is missing or disabled for you, you likely do not have the approval access group assigned. Request it through Odoo User Access and Security.\n5. If the order has been pending more than one working day with no clear reason, open a ticket under Odoo Workflow and Approval with the order number.'),

('odoo-access-denied', 'You are not allowed to access this document error', 'odoo-user-access-security',
'1. This means your Odoo user is missing an access group for that module or record, not that something is broken.\n2. Note the exact screen you were trying to open and the action you were performing (view, edit, create, or delete).\n3. Ask your department head to confirm you should have access to this screen as part of your role.\n4. Submit a ticket under Odoo User Access and Security with the screen name, your employee ID, department, and manager approval.\n5. Access changes are only applied by the MIS Head after manager confirmation, in line with least-privilege security practice, so unapproved requests will be declined.'),

('odoo-device-integration-not-syncing', 'Biometric device, weighing scale, or other equipment is not syncing with Odoo', 'odoo-api-integration',
'1. Confirm the device itself is powered on and connected to the network (check its display or status light).\n2. Restart the device once and wait two minutes for it to reconnect.\n3. On the PC or gateway running the integration service, confirm the integration application or service is still running.\n4. Check whether other devices of the same type are also affected; if only one device is affected the problem is usually local to that device.\n5. If the issue continues after a restart, open a ticket under Odoo API and Integration with the device name, location, and the time syncing stopped, so MIS can check the integration logs.'),

('odoo-slow-performance', 'Odoo is very slow, especially during shift change or peak hours', 'odoo-performance',
'1. Close browser tabs you are not using; each open Odoo tab uses its own connection.\n2. Avoid exporting very large lists (thousands of rows) during peak hours; use filters to narrow the list first.\n3. Clear your browser cache if a specific screen has been slow for more than a day, as old cached files can slow page loads.\n4. Check whether the slowness affects only you or the whole department; if it is only you, restart your PC and browser.\n5. If Odoo is slow for many users at the same time, this is usually a server load issue. Open a ticket under Odoo Performance immediately with the approximate time it started so MIS can check server usage.'),

('odoo-stock-count-mismatch', 'Stock quantity in Odoo does not match the physical warehouse count', 'odoo-inventory',
'1. Check Inventory > Reporting > Moves History for the item to see all recent stock movements and confirm nothing is still pending.\n2. Check whether there are unvalidated transfers (receipts, deliveries, or internal moves) still sitting in Ready or Waiting status; these do not update on-hand quantity until validated.\n3. Check for reserved quantity against open sales or manufacturing orders; reserved stock is not available even though it shows on hand.\n4. If the physical count is genuinely different, do not manually overwrite the quantity. Instead raise an Inventory Adjustment request through your warehouse supervisor.\n5. If the mismatch is large or repeats for the same item, open a ticket under Odoo Inventory with the item code, location, and both quantities so MIS can trace the movement history.'),

('odoo-mo-wont-complete', 'A manufacturing order will not complete or shows a component shortage', 'odoo-manufacturing',
'1. Open the manufacturing order and check the Components tab for any line marked in red or showing insufficient availability.\n2. Confirm the missing component has enough stock in the source location; if not, check with the warehouse or raise a purchase request.\n3. If stock exists but is not reserved, check whether it is in a different location or lot than the one the order expects.\n4. For a partial completion, use the Backorder option instead of forcing the quantity, so remaining components are tracked correctly on a follow-up order.\n5. If a component shows available stock in Odoo but the order still will not let you proceed, open a ticket under Odoo Manufacturing with the MO number.'),

('odoo-quality-check-missing', 'A quality check or quality alert is not appearing on a work order', 'odoo-quality',
'1. Quality checks only appear if a Quality Point has been configured for that product, operation, and work center combination. Confirm this combination matches the current order.\n2. Check the quality point Control Frequency setting; if it is set to a percentage rather than All, the check will only appear on some units, not every one.\n3. Confirm the quality point is Active and has not expired or been set to a date range that has already passed.\n4. To manually flag a defect outside a scheduled check, use the Quality Alert button available from the work order or product screen.\n5. If a quality point should exist but does not, or the results are not saving correctly, open a ticket under Odoo Quality with the product and work order number.'),

('odoo-rfq-po-bill-mismatch', 'A purchase order is not converting to a vendor bill correctly', 'odoo-purchase',
'1. Confirm the purchase order status is fully Received (the receipt has been validated), not just Confirmed.\n2. Compare the ordered quantity, received quantity, and billed quantity shown on the PO; Odoo uses a three-way match and will block or flag a bill if these do not agree.\n3. If the vendor billed a different quantity or price than the PO, update the bill manually with a note explaining the difference before validating it.\n4. Check whether the bill was created from the wrong PO if the vendor supplies multiple open orders at once.\n5. If quantities and prices all match but the bill still will not validate, open a ticket under Odoo Purchase with the PO and bill numbers.'),

('odoo-so-credit-blocked', 'A sales order cannot be confirmed due to a credit or customer block', 'odoo-sales',
'1. Check the banner or warning message on the sales order; it usually states whether it is a credit limit issue or the customer account itself is blocked.\n2. Confirm with Accounts whether the customer has overdue invoices, since credit limits are usually tied to unpaid balances.\n3. Sales staff cannot override a credit block themselves; the order must be sent to the Accounts or Sales Head for approval.\n4. If the block appears to be incorrect (for example, a payment was already received but not yet recorded), attach the payment proof when requesting the override.\n5. Open a ticket under Odoo Sales with the sales order number if the block remains after Accounts confirms the account should be clear.'),

('odoo-bank-reconciliation-mismatch', 'An invoice or payment will not reconcile with the bank statement', 'odoo-accounting',
'1. Confirm the payment amount, date, and reference on the bank statement line match the invoice or payment record in Odoo exactly; even a small rounding difference will block auto-matching.\n2. Check for a duplicate payment entry already reconciled against the same invoice.\n3. Use the manual reconciliation screen (Accounting > Reconciliation) to match the statement line to the correct invoice by hand if auto-matching fails.\n4. If a wrong journal entry was posted, do not delete it; ask Accounts to reverse it with a correcting entry so the audit trail stays intact.\n5. If the mismatch is still unclear after manual review, open a ticket under Odoo Accounting with the invoice number and bank statement line details.'),

('odoo-delivery-stuck-waiting', 'A delivery order is stuck in Waiting and cannot be validated', 'odoo-warehouse',
'1. A delivery stays in Waiting when the required stock is not yet reserved from the source location. Check Inventory > Reporting for on-hand quantity at that exact location.\n2. Check whether the stock exists but is reserved against a different, earlier order; reservations are normally first-in-first-out unless manually changed.\n3. If backorders are enabled, a partial delivery may proceed with the available quantity and create a backorder for the rest automatically.\n4. Avoid using Force Availability unless a supervisor confirms it, since it can reserve stock that is committed elsewhere and cause a second shortage.\n5. If the required stock genuinely exists and is not reserved elsewhere, open a ticket under Odoo Warehouse with the delivery order number.'),

('loom-production-entry-mismatch', 'Loom production entry does not match the planned efficiency', 'textile-weaving',
'1. Confirm the correct loom number and shift were selected before entering the production quantity; entries against the wrong loom will distort the efficiency figures for both looms.\n2. Efficiency percentage is calculated from actual picks or meters produced against the planned capacity for that loom and shift length; check whether planned capacity was set correctly for that loom.\n3. Downtime (machine stoppage, yarn breakage, power outage) must be logged separately in the downtime reason field; if it is left blank, the full shift counts as running time and lowers the efficiency figure incorrectly.\n4. If a shift entry was made against the wrong loom or shift by mistake, do not create a second entry to correct it. Ask your shift supervisor to request a correction, since production entries affect downstream costing.\n5. If the efficiency figure still looks wrong after checking the above, open a ticket under Textile Weaving with the loom number, shift, and date.'),

('dyeing-batch-recipe-missing', 'A dyeing batch recipe or shade record is missing in Odoo', 'textile-dyeing',
'1. Confirm the dyeing work order was created against the correct lot and shade code before production started; recipes are attached at the work order level.\n2. Check whether the recipe was saved as a draft and never confirmed; draft recipes do not appear on the production floor screen.\n3. For a shade-repeat request, search prior batches by customer and shade code rather than re-entering the recipe manually, to avoid a mismatched repeat.\n4. If a recipe was entered but is not visible to the dyeing floor terminal, confirm the correct work center was selected on the recipe screen.\n5. If a recipe is confirmed missing and needs to be recreated from a lab dip record, open a ticket under Textile Dyeing with the batch number and shade code.'),

('finishing-inspection-status-not-updating', 'Finishing or inspection status is not updating before dispatch', 'textile-finishing',
'1. Confirm every step of the inspection checklist for that lot has been completed and saved; a lot cannot move to Dispatch Cleared status while any checklist item is still open.\n2. Check whether the lot was split into multiple rolls or sub-lots; each sub-lot may need its own inspection entry.\n3. For a rejected or reprocessed lot, confirm it was routed back through the correct rework operation rather than marked complete directly, otherwise the system will keep flagging it.\n4. If the inspection was completed on paper but not entered into Odoo, enter it as soon as possible since dispatch and invoicing are blocked until the record exists.\n5. If the status still does not update after the checklist is complete, open a ticket under Textile Finishing with the lot number.'),

('production-plan-vs-actual-capacity', 'The production plan in Odoo does not reflect actual machine capacity', 'textile-planning',
'1. Check the working calendar assigned to the work center; planned capacity is calculated from the calendar hours, shift pattern, and number of machines configured for it.\n2. If a machine is under maintenance or was added or removed recently, its calendar and capacity must be updated, otherwise the plan will over or under allocate work to it.\n3. Confirm holidays and planned maintenance windows are marked on the calendar in advance so the planning engine does not schedule production during downtime.\n4. For a one-time capacity change (for example a machine running an extra shift for a rush order), this should be requested as a temporary calendar override rather than changed permanently.\n5. If the plan still does not match reality after the calendar is corrected, open a ticket under Textile Production Planning with the work center name and the dates affected.'),

('order-costing-incorrect', 'Order costing shows an incorrect material or process cost', 'textile-costing',
'1. Check which costing method is configured for the product (Standard, Average, or FIFO); each will show a different cost depending on when materials were purchased.\n2. Confirm the Bill of Materials used for the order has the current, approved material rates and process rates, not an outdated version.\n3. Landed costs such as freight or duty must be posted and allocated before the final cost is accurate; check whether a landed cost bill is still unposted.\n4. Check the unit of measure conversion on each BOM line; a wrong conversion (for example kilograms entered as meters) is one of the most common causes of a cost that looks far too high or too low.\n5. If the cost still looks wrong after checking the BOM, rates, and UoM, open a ticket under Textile Costing with the order number so MIS and Accounts can review the cost rollup together.')
ON CONFLICT (slug) DO UPDATE SET
  title = EXCLUDED.title,
  category = EXCLUDED.category,
  content = EXCLUDED.content;
